//
// Generated file, do not edit! Created by opp_msgtool 6.0 from FeedBackPacket.msg.
//

#ifndef __FEEDBACKPACKET_M_H
#define __FEEDBACKPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class FeedBackPacket;
/**
 * Class generated from <tt>FeedBackPacket.msg:1</tt> by opp_msgtool.
 * <pre>
 * packet FeedBackPacket
 * {
 *     int IncrementServiceTime;
 * }
 * </pre>
 */
class FeedBackPacket : public ::omnetpp::cPacket
{
  protected:
    int IncrementServiceTime = 0;

  private:
    void copy(const FeedBackPacket& other);

  protected:
    bool operator==(const FeedBackPacket&) = delete;

  public:
    FeedBackPacket(const char *name=nullptr, short kind=0);
    FeedBackPacket(const FeedBackPacket& other);
    virtual ~FeedBackPacket();
    FeedBackPacket& operator=(const FeedBackPacket& other);
    virtual FeedBackPacket *dup() const override {return new FeedBackPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getIncrementServiceTime() const;
    virtual void setIncrementServiceTime(int IncrementServiceTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FeedBackPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FeedBackPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline FeedBackPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<FeedBackPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __FEEDBACKPACKET_M_H

